import { createApp } from "vue";
import "./style.scss";
import "normalize.css";
import App from "./App.vue";
import pinia from "./store";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import settings from "./settings";
import { useTitle } from "@vueuse/core";
import "@/style/elemenet-style-overflow.scss";
import "@/style/common.scss";
useTitle(settings.webName);
let app = createApp(App);
app.use(pinia);
app.use(ElementPlus);
app.mount("#app");
